config/routes.rb
Rails.application.routes.draw do
    get '/webhook7PL9As3w9yZJQu4EWCfnkwzHqRJmm9F3NQz6RzHQSmkybvLgyqWHuhGLhke5au72' => 'bells#webhook'
    resources :bells
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bell.rb
class Bell < ApplicationRecord
    after_save :check_escalation

    private

    def check_escalation
        sql = "SELECT COUNT(*) FROM bells WHERE created_at >= now() - INTERVAL '1 min'"
        count = ActiveRecord::Base.connection.execute(sql)
        EscalationService.new.perform if count.values[0][0] == 1
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bells_controller.rb
class BellsController < ApplicationController
  before_action :set_bell, only: [:show, :edit, :update, :destroy]

  # GET /bells
  # GET /bells.json
  def index
    @bells = Bell.all
  end

  # GET /bells/1
  # GET /bells/1.json
  def show
  end

  # GET /bells/new
  def new
    @bell = Bell.new
  end

  # GET /bells/1/edit
  def edit
  end

  # POST /bells
  def webhook
    print "hi"
    @bell = Bell.new()
    @bell.save
    redirect_to "https://media.giphy.com/media/WsF061yAvIxA9krvvF/giphy.gif" 
  end
  # POST /bells.json
  def create
    @bell = Bell.new(bell_params)

    respond_to do |format|
      if @bell.save
        format.html { redirect_to @bell, notice: 'Bell was successfully created.' }
        format.json { render :show, status: :created, location: @bell }
      else
        format.html { render :new }
        format.json { render json: @bell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bells/1
  # PATCH/PUT /bells/1.json
  def update
    respond_to do |format|
      if @bell.update(bell_params)
        format.html { redirect_to @bell, notice: 'Bell was successfully updated.' }
        format.json { render :show, status: :ok, location: @bell }
      else
        format.html { render :edit }
        format.json { render json: @bell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bells/1
  # DELETE /bells/1.json
  def destroy
    @bell.destroy
    respond_to do |format|
      format.html { redirect_to bells_url, notice: 'Bell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bell
      @bell = Bell.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bell_params
      params.fetch(:bell, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bells_helper.rb
module BellsHelper
end

app/views/bells/_form.html.erb
<%= form_with(model: bell, local: true) do |form| %>
  <% if bell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bell.errors.count, "error") %> prohibited this bell from being saved:</h2>

      <ul>
        <% bell.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bells/edit.html.erb
<h1>Editing Bell</h1>

<%= render 'form', bell: @bell %>

<%= link_to 'Show', @bell %> |
<%= link_to 'Back', bells_path %>

app/views/bells/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bells</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bells.each do |bell| %>
      <tr>
        <td><%= link_to 'Show', bell %></td>
        <td><%= link_to 'Edit', edit_bell_path(bell) %></td>
        <td><%= link_to 'Destroy', bell, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bell', new_bell_path %>

app/views/bells/new.html.erb
<h1>New Bell</h1>

<%= render 'form', bell: @bell %>

<%= link_to 'Back', bells_path %>

app/views/bells/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bell_path(@bell) %> |
<%= link_to 'Back', bells_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartHome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>